### ISSUE TITLE
__init__.py in src

### ISSUE THREAD

**Issue by pulahd** [maxjcohen/transformer#13]
Hi,

I tried installing the library in google colab and was unable to run the training.py code.

Got the following error:
ModuleNotFoundError: No module named 'src'

As per the issue as discussed in 
https://stackoverflow.com/questions/8953844/import-module-from-subfolder
the reason for the above error could be the missing __init__.py file in src directory.

Thanks.

**Comment by maxjcohen** [comment]
Hi, the stack overflow thread you linked is 8 years old, and refers to an older python version than the one I (and colab) currently use. Creating a `__init__.py` is no longer required in python 3. Your error is due to something else.

I'm going on a hunch here, but if you loaded your colab, then ran `git clone`, your current working directory is not **in** the repo. You can fix this by running
```python
import os
os.chdir('transformer`)
```

Otherwise, you can consider sharing your colab, I'll help if I can.
