### ISSUE TITLE
question about decoder input

### ISSUE THREAD

**Issue by weiHelloWorld** [maxjcohen/transformer#41]
Hi,

Thanks for this excellent implementation!  

I have been playing with this model, and am wondering about a small detail regarding the decoder input.  In [here](https://github.com/maxjcohen/transformer/blob/master/tst/transformer.py#L139), you use the encoding output as the decoder input (which also serves as `memory` for the decoder layer [here](https://github.com/maxjcohen/transformer/blob/master/tst/transformer.py#L148)), instead of using the output target as the decoder input (as is given by `trg` in [this](https://towardsdatascience.com/how-to-code-the-transformer-in-pytorch-24db27c8f9ec) post for the translation task).  Do you have idea why we do not use output target as decoder inputs?  I assume that with proper masking, future information would not be included in the prediction, but am not sure if I miss anything.  Thank you!

**Comment by maxjcohen** [comment]
Hi, the decoder does indeed takes as input the output target in the original paper. But training the Transformer that way requires running an iterative prediction, i.e. predicting output variables at time `t`, and running the decoding with this additional prediction to get a prediction for `t+1`. Because we are dealing with very long time sequences, much longer than [usual sentences](http://proust-personnages.fr/?page_id=8986) (672 time steps for a month worth of data for instance), we can't afford this kind of computation cost.

Instead, I am treating the Transformer as an improved encoder-decoder architecture, inspired by [this paper](https://arxiv.org/abs/1409.0473).

**Comment by weiHelloWorld** [comment]
Got it, thanks for the explanation!
